In [ ]:
# 1. Average
df['marks'].mean()

# 3. Correlation
df['attendance'].corr(df['marks'])

# 4. New Column
df['Pass'] = df['marks'] >= 50

# 6. Plotting
import seaborn as sns
sns.histplot(df['marks'], kde=True)

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/student_performance_dataset_dirty.csv")

In [ ]:
df

    Student_ID        Name  Age  Marks  Attendance_Percentage
0            1   Student_1   23   56.0                   98.0
1            2   Student_2   21   62.0                   89.0
2            3   Student_3   22    NaN                   66.0
3            4   Student_4   23   86.0                   61.0
4            5   Student_5   21   94.0                   71.0
5            6   Student_6   18   64.0                    NaN
6            7   Student_7   21   53.0                   82.0
7            8         NaN   18   68.0                   99.0
8            9   Student_9   22   75.0                   63.0
9           10  Student_10   18   93.0                   98.0
10          11  Student_11  150   53.0                   96.0
11          12  Student_12   20   46.0                   98.0
12          13  Student_13   23  -10.0                   76.0
13          14  Student_14   19   91.0                   95.0
14          15  Student_15   18   84.0                   91.0
15          16  Student_16   22   65.0                  120.0
16          17  Student_17   19   94.0                   65.0
17          18  Student_18   22   45.0                   90.0
18          19  Student_19   21   93.0                   67.0
19          20  Student_20   23   99.0                   65.0
20           4   Student_4   23   86.0                   61.0

In [ ]:
df.head()

   Student_ID       Name  Age  Marks  Attendance_Percentage
0           1  Student_1   23   56.0                   98.0
1           2  Student_2   21   62.0                   89.0
2           3  Student_3   22    NaN                   66.0
3           4  Student_4   23   86.0                   61.0
4           5  Student_5   21   94.0                   71.0

In [ ]:
df.tail()

    Student_ID        Name  Age  Marks  Attendance_Percentage
16          17  Student_17   19   94.0                   65.0
17          18  Student_18   22   45.0                   90.0
18          19  Student_19   21   93.0                   67.0
19          20  Student_20   23   99.0                   65.0
20           4   Student_4   23   86.0                   61.0

In [ ]:
df.describe()

       Student_ID         Age      Marks  Attendance_Percentage
count   21.000000   21.000000  20.000000              20.000000
mean    10.190476   27.000000  69.850000              82.550000
std      5.938174   28.243583  25.882884              17.033944
min      1.000000   18.000000 -10.000000              61.000000
25%      5.000000   19.000000  55.250000              65.750000
50%     10.000000   21.000000  71.500000              85.500000
75%     15.000000   23.000000  91.500000              96.500000
max     20.000000  150.000000  99.000000             120.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             21 non-null     int64
 1   Name                   20 non-null     object
 2   Age                    21 non-null     int64
 3   Marks                  20 non-null     float64
 4   Attendance_Percentage  20 non-null     float64
dtypes: float64(2), int64(2), object(1)
memory usage: 972.0+ bytes

In [ ]:
#  Calculate the Average Marks
df["Marks"].mean()

np.float64(69.85)

In [ ]:
df["Attendance_Percentage"].mean()

np.float64(82.55)

In [ ]:
df.isnull()

    Student_ID   Name    Age  Marks  Attendance_Percentage
0        False  False  False  False                  False
1        False  False  False  False                  False
2        False  False  False   True                  False
3        False  False  False  False                  False
4        False  False  False  False                  False
5        False  False  False  False                   True
6        False  False  False  False                  False
7        False   True  False  False                  False
8        False  False  False  False                  False
9        False  False  False  False                  False
10       False  False  False  False                  False
11       False  False  False  False                  False
12       False  False  False  False                  False
13       False  False  False  False                  False
14       False  False  False  False                  False
15       False  False  False  False                  False
16       False  False  False  False                  False
17       False  False  False  False                  False
18       False  False  False  False                  False
19       False  False  False  False                  False
20       False  False  False  False                  False

In [ ]:
df.isnull().sum()

Student_ID               0
Name                     1
Age                      0
Marks                    1
Attendance_Percentage    1
dtype: int64

In [ ]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20     True
dtype: bool

In [ ]:
df[df.duplicated()]

    Student_ID       Name  Age  Marks  Attendance_Percentage
20           4  Student_4   23   86.0                   61.0

In [ ]:
df = df.drop_duplicates()

In [ ]:
df

    Student_ID        Name  Age  Marks  Attendance_Percentage
0            1   Student_1   23   56.0                   98.0
1            2   Student_2   21   62.0                   89.0
2            3   Student_3   22    NaN                   66.0
3            4   Student_4   23   86.0                   61.0
4            5   Student_5   21   94.0                   71.0
5            6   Student_6   18   64.0                    NaN
6            7   Student_7   21   53.0                   82.0
7            8         NaN   18   68.0                   99.0
8            9   Student_9   22   75.0                   63.0
9           10  Student_10   18   93.0                   98.0
10          11  Student_11  150   53.0                   96.0
11          12  Student_12   20   46.0                   98.0
12          13  Student_13   23  -10.0                   76.0
13          14  Student_14   19   91.0                   95.0
14          15  Student_15   18   84.0                   91.0
15          16  Student_16   22   65.0                  120.0
16          17  Student_17   19   94.0                   65.0
17          18  Student_18   22   45.0                   90.0
18          19  Student_19   21   93.0                   67.0
19          20  Student_20   23   99.0                   65.0

In [ ]:
df.dropna()

    Student_ID        Name  Age  Marks  Attendance_Percentage
0            1   Student_1   23   56.0                   98.0
1            2   Student_2   21   62.0                   89.0
3            4   Student_4   23   86.0                   61.0
4            5   Student_5   21   94.0                   71.0
6            7   Student_7   21   53.0                   82.0
8            9   Student_9   22   75.0                   63.0
9           10  Student_10   18   93.0                   98.0
10          11  Student_11  150   53.0                   96.0
11          12  Student_12   20   46.0                   98.0
12          13  Student_13   23  -10.0                   76.0
13          14  Student_14   19   91.0                   95.0
14          15  Student_15   18   84.0                   91.0
15          16  Student_16   22   65.0                  120.0
16          17  Student_17   19   94.0                   65.0
17          18  Student_18   22   45.0                   90.0
18          19  Student_19   21   93.0                   67.0
19          20  Student_20   23   99.0                   65.0

In [ ]:
df

    Student_ID        Name  Age  Marks  Attendance_Percentage
0            1   Student_1   23   56.0                   98.0
1            2   Student_2   21   62.0                   89.0
2            3   Student_3   22    NaN                   66.0
3            4   Student_4   23   86.0                   61.0
4            5   Student_5   21   94.0                   71.0
5            6   Student_6   18   64.0                    NaN
6            7   Student_7   21   53.0                   82.0
7            8         NaN   18   68.0                   99.0
8            9   Student_9   22   75.0                   63.0
9           10  Student_10   18   93.0                   98.0
10          11  Student_11  150   53.0                   96.0
11          12  Student_12   20   46.0                   98.0
12          13  Student_13   23  -10.0                   76.0
13          14  Student_14   19   91.0                   95.0
14          15  Student_15   18   84.0                   91.0
15          16  Student_16   22   65.0                  120.0
16          17  Student_17   19   94.0                   65.0
17          18  Student_18   22   45.0                   90.0
18          19  Student_19   21   93.0                   67.0
19          20  Student_20   23   99.0                   65.0

In [ ]:
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())

NameError: name 'df' is not defined

In [ ]:
df

    Student_ID        Name  Age  Marks  Attendance_Percentage
0            1   Student_1   23   56.0                   98.0
1            2   Student_2   21   62.0                   89.0
2            3   Student_3   22   69.0                   66.0
3            4   Student_4   23   86.0                   61.0
4            5   Student_5   21   94.0                   71.0
5            6   Student_6   18   64.0                    NaN
6            7   Student_7   21   53.0                   82.0
7            8         NaN   18   68.0                   99.0
8            9   Student_9   22   75.0                   63.0
9           10  Student_10   18   93.0                   98.0
10          11  Student_11  150   53.0                   96.0
11          12  Student_12   20   46.0                   98.0
12          13  Student_13   23  -10.0                   76.0
13          14  Student_14   19   91.0                   95.0
14          15  Student_15   18   84.0                   91.0
15          16  Student_16   22   65.0                  120.0
16          17  Student_17   19   94.0                   65.0
17          18  Student_18   22   45.0                   90.0
18          19  Student_19   21   93.0                   67.0
19          20  Student_20   23   99.0                   65.0

In [ ]:
df["Marks"].mean()

np.float64(69.0)

In [ ]:
df["Name"] = df["Name"].fillna("Student_8")

In [ ]:
df

    Student_ID        Name  Age  Marks  Attendance_Percentage
0            1   Student_1   23   56.0                   98.0
1            2   Student_2   21   62.0                   89.0
2            3   Student_3   22   69.0                   66.0
3            4   Student_4   23   86.0                   61.0
4            5   Student_5   21   94.0                   71.0
5            6   Student_6   18   64.0                    NaN
6            7   Student_7   21   53.0                   82.0
7            8   Student_8   18   68.0                   99.0
8            9   Student_9   22   75.0                   63.0
9           10  Student_10   18   93.0                   98.0
10          11  Student_11  150   53.0                   96.0
11          12  Student_12   20   46.0                   98.0
12          13  Student_13   23  -10.0                   76.0
13          14  Student_14   19   91.0                   95.0
14          15  Student_15   18   84.0                   91.0
15          16  Student_16   22   65.0                  120.0
16          17  Student_17   19   94.0                   65.0
17          18  Student_18   22   45.0                   90.0
18          19  Student_19   21   93.0                   67.0
19          20  Student_20   23   99.0                   65.0

In [ ]:
df[df.duplicated()]

Empty DataFrame
Columns: [Student_ID, Name, Age, Marks, Attendance_Percentage]
Index: []

In [ ]:
df.loc[df["Attendance_Percentage"] > 100, "Attendance_Percentage"] = df["Attendance_Percentage"].mean()

In [ ]:
df

    Student_ID        Name   Age  Marks  Attendance_Percentage
0            1   Student_1  23.0  69.00              83.684211
1            2   Student_2  21.0  69.00              83.684211
2            3   Student_3  22.0  69.00              83.684211
3            4   Student_4  23.0  69.00              83.684211
4            5   Student_5  21.0  69.00              83.684211
5            6   Student_6  18.0  69.00              83.684211
6            7   Student_7  21.0  69.00              83.684211
7            8   Student_8  18.0  69.00              83.684211
8            9   Student_9  22.0  69.00              83.684211
9           10  Student_10  18.0  69.00              83.684211
10          11  Student_11  27.2  69.00              83.684211
11          12  Student_12  20.0  69.00              83.684211
12          13  Student_13  23.0  65.05              83.684211
13          14  Student_14  19.0  69.00              83.684211
14          15  Student_15  18.0  69.00              83.684211
15          16  Student_16  22.0  69.00              83.684211
16          17  Student_17  19.0  69.00              83.684211
17          18  Student_18  22.0  69.00              83.684211
18          19  Student_19  21.0  69.00              83.684211
19          20  Student_20  23.0  69.00              83.684211

In [ ]:
df[df["Age"] > 30]

Empty DataFrame
Columns: [Student_ID, Name, Age, Marks, Attendance_Percentage]
Index: []

In [ ]:
df.loc[df["Age"] > 30, "Age"] = df["Age"].mean()

In [ ]:
df

    Student_ID        Name   Age  Marks  Attendance_Percentage
0            1   Student_1  23.0   56.0              98.000000
1            2   Student_2  21.0   62.0              89.000000
2            3   Student_3  22.0   69.0              66.000000
3            4   Student_4  23.0   86.0              61.000000
4            5   Student_5  21.0   94.0              71.000000
5            6   Student_6  18.0   64.0              83.684211
6            7   Student_7  21.0   53.0              82.000000
7            8   Student_8  18.0   68.0              99.000000
8            9   Student_9  22.0   75.0              63.000000
9           10  Student_10  18.0   93.0              98.000000
10          11  Student_11  27.2   53.0              96.000000
11          12  Student_12  20.0   46.0              98.000000
12          13  Student_13  23.0  -10.0              76.000000
13          14  Student_14  19.0   91.0              95.000000
14          15  Student_15  18.0   84.0              91.000000
15          16  Student_16  22.0   65.0             120.000000
16          17  Student_17  19.0   94.0              65.000000
17          18  Student_18  22.0   45.0              90.000000
18          19  Student_19  21.0   93.0              67.000000
19          20  Student_20  23.0   99.0              65.000000

In [ ]:
df.loc[df["Marks"] < 0, "Marks"] = df["Marks"].mean()

In [ ]:
df

    Student_ID        Name   Age  Marks  Attendance_Percentage
0            1   Student_1  23.0  69.00              98.000000
1            2   Student_2  21.0  69.00              89.000000
2            3   Student_3  22.0  69.00              66.000000
3            4   Student_4  23.0  69.00              61.000000
4            5   Student_5  21.0  69.00              71.000000
5            6   Student_6  18.0  69.00              83.684211
6            7   Student_7  21.0  69.00              82.000000
7            8   Student_8  18.0  69.00              99.000000
8            9   Student_9  22.0  69.00              63.000000
9           10  Student_10  18.0  69.00              98.000000
10          11  Student_11  27.2  69.00              96.000000
11          12  Student_12  20.0  69.00              98.000000
12          13  Student_13  23.0  65.05              76.000000
13          14  Student_14  19.0  69.00              95.000000
14          15  Student_15  18.0  69.00              91.000000
15          16  Student_16  22.0  69.00             120.000000
16          17  Student_17  19.0  69.00              65.000000
17          18  Student_18  22.0  69.00              90.000000
18          19  Student_19  21.0  69.00              67.000000
19          20  Student_20  23.0  69.00              65.000000